- hosts: all
  gather_facts: False

  tasks:
    - name: Instalando docker
      apt:
        name: docker.io
        update_cache: yes
        state: present

    - name: Instalando docker-compose
      apt:
        name: docker-compose
        update_cache: yes
        state: present

    - name: Habilitar docker no boot
      service:
        name: docker
        enabled: yes
        state: started

    - name: Add docker group on ubuntu user
      user:
        name: ubuntu
        groups: docker

    - name: Pull an image
      command: "docker run {{ docker_image }}"
      register: docker_return

    - name: Exibindo variaveis
      debug:
        msg: "{{ docker_return }} "

    - name: Exibindo docker ps
      command: "docker ps -a"
      register: docker_ps

    - name: Docker PS output
      debug: 
         msg: "{{ docker_ps }}"
