- hosts: all
  gather_facts: False

  tasks:
    - name: Pull an image
      command: "docker run {{ docker_image }}"
      register: docker_return

    - name: Exibindo variaveis
      debug:
        msg: "{{ docker_return }} "
