- hosts: all
  gather_facts: False

  tasks:
    - name: Instalando docker
      apt:
        name: docker.io
        update_cache: yes
        state: present

    - name: Instalando docker-compose
      apt:
        name: docker-compose
        update_cache: yes
        state: present

    - name: Habilitar docker no boot
      service:
        name: docker
        enabled: yes
        state: started

    - name: Add docker group on ubuntu user
      user:
        name: ubuntu
        groups: docker

    - name: Docker Login
      command: "cat {{ GCP_CREDENTIAL }} | docker login docker login -u _json_key --password-stdin https://gcr.io"
      register: docker_login

    - name: Docker Login debug
      debug:
        msg: "{{ GCP_CREDENTIAL }}"

    - name: Pull an image
      command: "docker run {{ docker_image }}"
      register: docker_return

    - name: Exibindo variaveis
      debug:
        msg: "{{ docker_return }} "
